### ISSUE TITLE
自定义 registerHelper 如何导出？页面编译报错无法识别自定义helpers

### ISSUE THREAD

**Issue by luran813** [framework7io/framework7-loader#2]

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. 

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.

It will save a lot of time for other contributors to check your issue and fix it.
